### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by chin123** [chin123/gpa#1]
A list of features done, and left to be done:
- [x] more generic searching with filters
  * [x] collapsable filter menu
  * [x] check if search doesn't match course, then display clickable list with courses
- [x] regex search support
- [x] hover on prof shows specific stats, semester, curve etc
  * [x] plot curve per professor
  * [x] figure out how to do html image popup on hover without js
- [x] link to course explorer on selected course
- [ ] make graph have hover tooltips (unknown difficulty without js)
- [x] Recognize multiple unique courses using same number and subject
- [x] Offered in Fall 2020 Feature
- [x] GPA per semester
- [x] +/- grades
- [x] Link to latest course explorer page  
- [ ] Automated testing. There is no JS so it should be easy to do using requests and beautiful soup.

**Comment by abhinavtripathy** [comment]
@chin123 Are you looking for collaborators on this open source project or are you doing this all by yourself? Also kudos on the great idea as well as implementation!

**Comment by chin123** [comment]
Hey @abhinavtripathy ,
Pull requests are always welcome! Please make an issue before you start anything though, to make sure that everyone knows what you're implementing.  
Furthermore, there are a couple of features of the front end I would like to stay the same:
* 0 javascript: improves speed and accessibility, and reduces complexity
* no animations  
  
Right now @dineshkumar227 is working on hover for prof specific stats, semester, curve etc.
